# Generated by Django 5.0.1 on 2025-09-29 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0019_alter_student_guardian_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="الحالة (نشط)"),
        ),
        migrations.CreateModel(
            name="StudentSuspension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاريخ بدء التجميد")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ انتهاء التجميد"
                    ),
                ),
                (
                    "student_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspensions",
                        to="school_app.studentgroup",
                        verbose_name="تسجيل الطالب في الفوج",
                    ),
                ),
            ],
            options={
                "verbose_name": "فترة تجميد الطالب",
                "verbose_name_plural": "فترات تجميد الطلاب",
                "ordering": ["-start_date"],
            },
        ),
    ]
