# Generated by Django 5.0.1 on 2025-09-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school_app", "0020_studentgroup_is_active_studentsuspension"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="is_free",
            field=models.BooleanField(default=False, verbose_name="تسجيل مجاني"),
        ),
    ]
